# Generated by Django 5.0.7 on 2024-07-31 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='embed',
            field=models.TextField(unique=True),
        ),
    ]
